
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBJump
{
    private readonly System.Collections.Generic.Dictionary<int, Jump> _dataMap;
    private readonly System.Collections.Generic.List<Jump> _dataList;
    
    public TBJump(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Jump>();
        _dataList = new System.Collections.Generic.List<Jump>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Jump _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Jump.DeserializeJump(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Jump> DataMap => _dataMap;
    public System.Collections.Generic.List<Jump> DataList => _dataList;

    public Jump GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Jump Get(int key) => _dataMap[key];
    public Jump this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

