
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EquipmentType
    {
        /// <summary>
        /// 左手武器
        /// </summary>
        LeftWeapon = 0,
        /// <summary>
        /// 右手武器
        /// </summary>
        RightWeapon = 1,
        /// <summary>
        /// 手套
        /// </summary>
        Gloves = 2,
        /// <summary>
        /// 头盔
        /// </summary>
        Helmet = 3,
        /// <summary>
        /// 衣服
        /// </summary>
        Clothes = 4,
        /// <summary>
        /// 腿
        /// </summary>
        Leg = 5,
    }

} 

