
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Icon : Luban.BeanBase
{
    public Icon(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["imageName"].IsString) { throw new SerializationException(); }  ImageName = _buf["imageName"]; }
    }

    public static Icon DeserializeIcon(JSONNode _buf)
    {
        return new Icon(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 图标名称
    /// </summary>
    public readonly string ImageName;
   
    public const int __ID__ = 2273433;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "imageName:" + ImageName + ","
        + "}";
    }
}

}
