
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MultiLanguageTexture : Luban.BeanBase
{
    public MultiLanguageTexture(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["chinese"].IsNumber) { throw new SerializationException(); }  Chinese = _buf["chinese"]; }
        { if(!_buf["traditionalChinese"].IsNumber) { throw new SerializationException(); }  TraditionalChinese = _buf["traditionalChinese"]; }
        { if(!_buf["english"].IsNumber) { throw new SerializationException(); }  English = _buf["english"]; }
        { if(!_buf["korean"].IsNumber) { throw new SerializationException(); }  Korean = _buf["korean"]; }
        { if(!_buf["russian"].IsNumber) { throw new SerializationException(); }  Russian = _buf["russian"]; }
        { if(!_buf["german"].IsNumber) { throw new SerializationException(); }  German = _buf["german"]; }
        { if(!_buf["vietnamese"].IsNumber) { throw new SerializationException(); }  Vietnamese = _buf["vietnamese"]; }
        { if(!_buf["thai"].IsNumber) { throw new SerializationException(); }  Thai = _buf["thai"]; }
        { if(!_buf["french"].IsNumber) { throw new SerializationException(); }  French = _buf["french"]; }
        { if(!_buf["japanese"].IsNumber) { throw new SerializationException(); }  Japanese = _buf["japanese"]; }
        { if(!_buf["spanish"].IsNumber) { throw new SerializationException(); }  Spanish = _buf["spanish"]; }
        { if(!_buf["arabic"].IsNumber) { throw new SerializationException(); }  Arabic = _buf["arabic"]; }
    }

    public static MultiLanguageTexture DeserializeMultiLanguageTexture(JSONNode _buf)
    {
        return new MultiLanguageTexture(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 简体中文
    /// </summary>
    public readonly int Chinese;
    /// <summary>
    /// 繁体中文
    /// </summary>
    public readonly int TraditionalChinese;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly int English;
    /// <summary>
    /// 韩文
    /// </summary>
    public readonly int Korean;
    /// <summary>
    /// 俄语
    /// </summary>
    public readonly int Russian;
    /// <summary>
    /// 德语
    /// </summary>
    public readonly int German;
    /// <summary>
    /// 越南语
    /// </summary>
    public readonly int Vietnamese;
    /// <summary>
    /// 泰语
    /// </summary>
    public readonly int Thai;
    /// <summary>
    /// 法语
    /// </summary>
    public readonly int French;
    /// <summary>
    /// 日语
    /// </summary>
    public readonly int Japanese;
    /// <summary>
    /// 西班牙语
    /// </summary>
    public readonly int Spanish;
    /// <summary>
    /// 阿拉伯语
    /// </summary>
    public readonly int Arabic;
   
    public const int __ID__ = -817445814;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "chinese:" + Chinese + ","
        + "traditionalChinese:" + TraditionalChinese + ","
        + "english:" + English + ","
        + "korean:" + Korean + ","
        + "russian:" + Russian + ","
        + "german:" + German + ","
        + "vietnamese:" + Vietnamese + ","
        + "thai:" + Thai + ","
        + "french:" + French + ","
        + "japanese:" + Japanese + ","
        + "spanish:" + Spanish + ","
        + "arabic:" + Arabic + ","
        + "}";
    }
}

}
