
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RewardTemplate : Luban.BeanBase
{
    public RewardTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.List<TBReward>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { TBReward __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = TBReward.DeserializeTBReward(__e0);  }  Rewards.Add(__v0); }   }
    }

    public static RewardTemplate DeserializeRewardTemplate(JSONNode _buf)
    {
        return new RewardTemplate(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 奖励列表
    /// </summary>
    public readonly System.Collections.Generic.List<TBReward> Rewards;
   
    public const int __ID__ = -646140695;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}
