
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TBEmptyGoTo TBEmptyGoTo {get; }
    public TBPopupWindow TBPopupWindow {get; }
    public TBSkill TBSkill {get; }
    public TBBuff TBBuff {get; }
    public TBSubobject TBSubobject {get; }
    public TBLanguage TBLanguage {get; }
    public TBIcon TBIcon {get; }
    public TBTexture TBTexture {get; }
    public TBMultiLanguageTexture TBMultiLanguageTexture {get; }
    public TBPanel TBPanel {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TBEmptyGoTo = new TBEmptyGoTo(loader("tbemptygoto"));
        TBPopupWindow = new TBPopupWindow(loader("tbpopupwindow"));
        TBSkill = new TBSkill(loader("tbskill"));
        TBBuff = new TBBuff(loader("tbbuff"));
        TBSubobject = new TBSubobject(loader("tbsubobject"));
        TBLanguage = new TBLanguage(loader("tblanguage"));
        TBIcon = new TBIcon(loader("tbicon"));
        TBTexture = new TBTexture(loader("tbtexture"));
        TBMultiLanguageTexture = new TBMultiLanguageTexture(loader("tbmultilanguagetexture"));
        TBPanel = new TBPanel(loader("tbpanel"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TBEmptyGoTo.ResolveRef(this);
        TBPopupWindow.ResolveRef(this);
        TBSkill.ResolveRef(this);
        TBBuff.ResolveRef(this);
        TBSubobject.ResolveRef(this);
        TBLanguage.ResolveRef(this);
        TBIcon.ResolveRef(this);
        TBTexture.ResolveRef(this);
        TBMultiLanguageTexture.ResolveRef(this);
        TBPanel.ResolveRef(this);
    }
}

}
