
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// buff
/// </summary>
public sealed partial class TBBuffValue : Luban.BeanBase
{
    public TBBuffValue(JSONNode _buf) 
    {
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (ValuePropertyType)_buf["type"].AsInt; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static TBBuffValue DeserializeTBBuffValue(JSONNode _buf)
    {
        return new TBBuffValue(_buf);
    }

    /// <summary>
    /// 值属性类型
    /// </summary>
    public readonly ValuePropertyType Type;
    /// <summary>
    /// 值
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = 1346076176;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "value:" + Value + ","
        + "}";
    }
}

}
