
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBIcon
{
    private readonly System.Collections.Generic.Dictionary<int, Icon> _dataMap;
    private readonly System.Collections.Generic.List<Icon> _dataList;
    
    public TBIcon(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Icon>();
        _dataList = new System.Collections.Generic.List<Icon>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Icon _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Icon.DeserializeIcon(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Icon> DataMap => _dataMap;
    public System.Collections.Generic.List<Icon> DataList => _dataList;

    public Icon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Icon Get(int key) => _dataMap[key];
    public Icon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

