
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBMultiLanguageTexture
{
    private readonly System.Collections.Generic.Dictionary<int, MultiLanguageTexture> _dataMap;
    private readonly System.Collections.Generic.List<MultiLanguageTexture> _dataList;
    
    public TBMultiLanguageTexture(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MultiLanguageTexture>();
        _dataList = new System.Collections.Generic.List<MultiLanguageTexture>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MultiLanguageTexture _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = MultiLanguageTexture.DeserializeMultiLanguageTexture(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MultiLanguageTexture> DataMap => _dataMap;
    public System.Collections.Generic.List<MultiLanguageTexture> DataList => _dataList;

    public MultiLanguageTexture GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MultiLanguageTexture Get(int key) => _dataMap[key];
    public MultiLanguageTexture this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

