
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBSkill
{
    private readonly System.Collections.Generic.Dictionary<int, Skill> _dataMap;
    private readonly System.Collections.Generic.List<Skill> _dataList;
    
    public TBSkill(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Skill>();
        _dataList = new System.Collections.Generic.List<Skill>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Skill _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Skill.DeserializeSkill(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.SkillId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Skill> DataMap => _dataMap;
    public System.Collections.Generic.List<Skill> DataList => _dataList;

    public Skill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Skill Get(int key) => _dataMap[key];
    public Skill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

