
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Texture : Luban.BeanBase
{
    public Texture(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["textureName"].IsString) { throw new SerializationException(); }  TextureName = _buf["textureName"]; }
    }

    public static Texture DeserializeTexture(JSONNode _buf)
    {
        return new Texture(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 图片名称
    /// </summary>
    public readonly string TextureName;
   
    public const int __ID__ = 246836475;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "textureName:" + TextureName + ","
        + "}";
    }
}

}
