
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBTexture
{
    private readonly System.Collections.Generic.Dictionary<int, Texture> _dataMap;
    private readonly System.Collections.Generic.List<Texture> _dataList;
    
    public TBTexture(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Texture>();
        _dataList = new System.Collections.Generic.List<Texture>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Texture _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Texture.DeserializeTexture(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Texture> DataMap => _dataMap;
    public System.Collections.Generic.List<Texture> DataList => _dataList;

    public Texture GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Texture Get(int key) => _dataMap[key];
    public Texture this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

